-- access_links: empty

-- admins: empty

-- blocked_users: empty

INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (1, 0, 'جزوه دروس تخصصی و پایه', 'folder', 0, 1, 0, NULL, NULL, '2026-07-29 20:58:53', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (2, 0, 'جزوه دروس عمومی', 'none', 0, 1, 0, NULL, NULL, '2026-07-29 21:16:50', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (3, 0, 'کارآموزی', 'none', 0, 1, 0, NULL, NULL, '2026-07-29 21:41:39', 'random', NULL, 1, '2026-07-31T17:11:00.783Z', '6747478812.0', 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (4, 0, 'کارآموزی', 'none', 0, 1, 0, NULL, NULL, '2026-07-29 21:49:07', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (5, 0, 'کارآموزی', 'none', 0, 1, 0, NULL, NULL, '2026-07-29 22:14:26', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (6, 0, '1', 'none', 0, 1, 0, NULL, NULL, '2026-07-29 23:21:47', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (7, 0, '2', 'none', 0, 1, 0, NULL, NULL, '2026-07-29 23:36:19', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (8, 0, '3', 'none', 0, 1, 0, NULL, NULL, '2026-07-30 08:59:09', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (9, 0, '4', 'folder', 0, 1, 0, NULL, NULL, '2026-07-30 09:12:20', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (10, 0, '5', 'folder', 0, 1, 0, NULL, NULL, '2026-07-30 09:22:51', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (11, 10, '5.1', 'folder', 0, 1, 0, NULL, NULL, '2026-07-30 09:23:05', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (12, 1, 'شاخه1', 'content', 0, 1, 0, NULL, NULL, '2026-07-30 09:46:57', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (13, 1, 'zir2', 'none', 0, 1, 0, NULL, NULL, '2026-07-30 09:57:58', 'random', NULL, 1, '2026-08-01T15:31:23.344Z', '6747478812.0', 0, NULL, NULL, 13, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (14, 1, 'zir3', 'none', 0, 1, 0, NULL, NULL, '2026-07-30 09:59:50', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (15, 10, '5.2', 'none', 0, 1, 0, NULL, NULL, '2026-07-30 10:00:19', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (16, 10, '5.3', 'none', 0, 1, 0, NULL, NULL, '2026-07-30 10:00:50', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (17, 9, '4.1', 'none', 0, 1, 0, NULL, NULL, '2026-07-30 10:59:02', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (18, 9, '4.2', 'folder', 0, 1, 0, NULL, NULL, '2026-07-30 10:59:27', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (19, 18, '4.2.1', 'none', 0, 1, 0, NULL, NULL, '2026-07-30 11:00:20', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (20, 18, '4.2.2', 'folder', 0, 1, 0, NULL, NULL, '2026-07-30 11:00:51', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (21, 18, '4.2.3', 'none', 0, 1, 0, NULL, NULL, '2026-07-30 11:01:07', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (22, 20, '4.2.2.a', 'content', 0, 1, 0, NULL, NULL, '2026-07-30 11:01:52', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 22, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (23, 20, '4.2.2.b', 'none', 0, 1, 0, NULL, NULL, '2026-07-30 11:28:43', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (24, 0, '6', 'folder', 0, 1, 0, NULL, NULL, '2026-07-30 14:00:16', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (25, 24, '6.1', 'folder', 0, 1, 0, NULL, NULL, '2026-07-30 14:00:46', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (26, 24, '6.2 بعد از ایجاد قابلیت تغییر نام', 'content', 0, 1, 0, NULL, NULL, '2026-07-30 14:17:26', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (27, 25, '6.1.1', 'none', 0, 1, 0, NULL, NULL, '2026-07-30 14:18:18', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (28, 0, '7', 'folder', 0, 1, 0, NULL, NULL, '2026-07-30 14:39:03', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (29, 28, '7.1', 'content', 0, 1, 0, NULL, NULL, '2026-07-30 14:39:24', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (30, 28, '7.2', 'input', 0, 1, 0, NULL, NULL, '2026-07-30 14:39:44', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (31, 28, '7.3', 'folder', 0, 1, 0, NULL, NULL, '2026-07-30 14:54:37', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (32, 31, '7.3.1', 'content', 0, 1, 0, NULL, NULL, '2026-07-30 14:55:45', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (33, 28, '7.4', 'content', 0, 1, 0, NULL, NULL, '2026-07-30 16:17:39', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (34, 0, '8', 'content', 0, 1, 0, NULL, NULL, '2026-08-02 23:28:04', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 34, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (35, 34, '8.1', 'folder', 0, 1, 0, NULL, NULL, '2026-08-02 23:28:20', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 34, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (36, 34, '8.2', 'folder', 0, 1, 0, NULL, NULL, '2026-08-02 23:28:37', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 34, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (37, 35, '8.1.1', 'content', 0, 1, 0, NULL, NULL, '2026-08-02 23:31:48', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 34, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (38, 35, '8.1.2', 'content', 0, 1, 0, NULL, NULL, '2026-08-02 23:33:17', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 34, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (39, 36, '8.2.1', 'folder', 0, 1, 0, NULL, NULL, '2026-08-02 23:33:48', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 34, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (40, 36, '8.2.2', 'none', 0, 1, 0, NULL, NULL, '2026-08-02 23:34:12', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 34, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (41, 39, '8.2.1.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-03 00:19:22', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 34, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (42, 39, '8.2.1.2', 'none', 0, 1, 0, NULL, NULL, '2026-08-03 00:19:39', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 34, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (43, 0, '9', 'folder', 0, 1, 0, NULL, NULL, '2026-08-03 03:04:18', 'random', NULL, 1, '2026-08-03T03:30:45.834Z', '6747478812.0', 0, NULL, NULL, 43, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (44, 43, '9.1', 'folder', 0, 1, 0, NULL, NULL, '2026-08-03 03:04:43', 'random', NULL, 1, '2026-08-03T03:30:00.624Z', '6747478812.0', 0, NULL, NULL, 44, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (45, 0, '10', 'content', 0, 1, 0, NULL, NULL, '2026-08-03 03:05:59', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 45, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (46, 44, '9.1.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-03 03:29:01', 'random', NULL, 1, '2026-08-03T03:29:39.663Z', '6747478812.0', 0, NULL, NULL, 46, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (47, 0, '11', 'content', 0, 1, 0, NULL, NULL, '2026-08-03 03:38:00', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 47, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (48, 47, '11-1', 'none', 0, 1, 0, NULL, NULL, '2026-08-03 03:38:12', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 47, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (49, 47, '11-2', 'none', 0, 1, 0, NULL, NULL, '2026-08-03 03:38:20', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 47, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (50, 0, '12', 'content', 0, 1, 0, NULL, NULL, '2026-08-03 13:24:20', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (51, 50, '12.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-03 13:26:29', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (52, 0, '13', 'content', 0, 1, 0, NULL, NULL, '2026-08-03 13:28:20', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (53, 0, '14', 'input', 0, 1, 0, NULL, NULL, '2026-08-03 13:30:31', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (54, 0, '15', 'content', 0, 1, 0, NULL, NULL, '2026-08-03 16:32:53', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (55, 54, '15.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-03 16:33:26', 'random', NULL, 1, '2026-08-03T16:44:37.527Z', '6747478812.0', 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (56, 0, '16', 'mixed', 0, 1, 0, NULL, NULL, '2026-08-03 17:36:52', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, 'mixed,content');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (57, 56, '16.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-03 17:37:29', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (58, 0, '17', 'mixed', 0, 1, 0, NULL, NULL, '2026-08-05 23:00:53', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, 'folder,content,link,input');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (59, 58, '17.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-05 23:10:23', 'random', NULL, 1, '2026-08-05T23:12:59.056Z', '6747478812.0', 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (60, 0, '18', 'input', 0, 1, 0, NULL, NULL, '2026-08-05 23:29:34', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (61, 60, '18.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-05 23:29:53', 'random', NULL, 1, '2026-08-05T23:31:17.873Z', '6747478812.0', 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (62, 0, '19', 'link', 0, 1, 0, NULL, NULL, '2026-08-06 00:21:07', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, 'folder,content,input');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (63, 62, '19.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 00:21:45', 'random', NULL, 1, '2026-08-06T00:23:56.141Z', '6747478812.0', 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (64, 0, '20', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 00:46:31', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (65, 64, '20.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 00:47:07', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (66, 0, '21', 'link', 0, 1, 0, NULL, NULL, '2026-08-06 00:50:17', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (67, 66, '21.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 00:51:09', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (68, 0, '22', 'link', 0, 1, 0, NULL, NULL, '2026-08-06 01:08:06', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (69, 68, '22.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 01:08:37', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (70, 0, 'A', 'input', 0, 1, 0, NULL, NULL, '2026-08-06 01:19:54', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (71, 70, 'A.a', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 01:20:21', 'random', NULL, 1, '2026-08-06T01:46:27.936Z', '6747478812.0', 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (72, 0, '23', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 01:48:06', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (73, 72, '23.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 01:48:23', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (74, 0, '24', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 02:22:20', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (75, 74, '24.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 02:22:48', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (76, 0, '25', 'folder', 0, 1, 0, NULL, NULL, '2026-08-06 02:28:03', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (77, 0, '26', 'link', 0, 1, 0, NULL, NULL, '2026-08-06 02:31:51', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (78, 0, '27', 'folder', 0, 1, 0, NULL, NULL, '2026-08-06 02:34:37', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (79, 78, '27.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 02:34:48', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (80, 0, '28', 'content', 0, 1, 0, NULL, NULL, '2026-08-06 02:35:28', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (81, 0, '29', 'folder', 0, 1, 0, NULL, NULL, '2026-08-06 02:36:55', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (82, 0, '30', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 02:37:37', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (83, 0, '31', 'input', 0, 1, 0, NULL, NULL, '2026-08-06 02:46:41', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (84, 0, '32', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 03:09:37', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (85, 84, '32.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 03:09:49', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (86, 0, '33', 'link', 0, 1, 0, NULL, NULL, '2026-08-06 03:16:54', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (87, 0, '34', 'link', 0, 1, 0, NULL, NULL, '2026-08-06 03:25:53', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (88, 87, '34.1', 'none', 0, 1, 0, NULL, NULL, '2026-08-06 03:28:22', 'random', NULL, 1, '2026-08-06T03:29:57.403Z', '6747478812.0', 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (89, 0, '35', 'input', 0, 1, 0, NULL, NULL, '2026-08-06 03:44:44', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (90, 0, '36', 'link', 0, 1, 0, NULL, NULL, '2026-08-06 03:45:44', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (91, 0, '37', 'input', 0, 1, 0, NULL, NULL, '2026-08-06 03:47:34', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (92, 0, '38', 'input', 0, 1, 0, NULL, NULL, '2026-08-06 03:50:45', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (93, 0, '39', 'input', 0, 1, 0, NULL, NULL, '2026-08-06 03:52:20', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, NULL);
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (94, 0, '40', 'content', 0, 1, 0, NULL, NULL, '2026-08-06 05:22:49', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, 'folder,content');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (95, 94, '40.1', 'folder', 0, 1, 0, NULL, NULL, '2026-08-06 05:23:08', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (96, 94, '40.2', 'content', 0, 1, 0, NULL, NULL, '2026-08-06 05:23:21', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (97, 95, '40.1.1', 'content', 0, 1, 0, NULL, NULL, '2026-08-06 05:24:12', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (98, 95, '40.1.2', 'content', 0, 1, 0, NULL, NULL, '2026-08-06 05:24:23', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (99, 0, '41', 'none', 0, 1, 0, NULL, NULL, '2026-09-17 15:12:33', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');
INSERT INTO "buttons" ("id", "parent_id", "title", "mode", "position", "visible", "locked", "command", "link", "created_at", "content_order", "description", "deleted", "deleted_at", "deleted_by", "original_parent_id", "updated_at", "updated_by", "deleted_root_id", "types") VALUES (100, 0, '41', 'content', 0, 1, 0, NULL, NULL, '2026-09-17 15:12:33', 'random', NULL, 0, NULL, NULL, 0, NULL, NULL, 0, '');

-- chats: empty

INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (1, 22, NULL, 'text', 'ای', 0, '2026-07-30 12:33:13', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (2, 22, NULL, 'text', 'تندر آقای', 0, '2026-07-30 12:33:40', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (3, 22, NULL, 'text', 'ای', 0, '2026-07-30 12:34:09', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (4, 22, 'AgACAgQAAxkBAAIBUWprQZeo5Y8vwj8q-e9j2QWG8BarAAL5D2sb42hZUzt1KLOgVYoHAQADAgADeQADPQQ', 'photo', NULL, 0, '2026-07-30 12:41:19', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (5, 22, 'BAACAgQAAxkBAAIBbGprRreZxzzZ8v7_NhWl9X5k0ZkWAAJdHAAC42hZU8XgWtSQoPRoPQQ', 'video', NULL, 0, '2026-07-30 12:42:31', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (6, 22, 'BAACAgQAAxkBAAIBbGprRreZxzzZ8v7_NhWl9X5k0ZkWAAJdHAAC42hZU8XgWtSQoPRoPQQ', 'video', NULL, 0, '2026-07-30 12:43:22', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (7, 22, 'AgACAgQAAxkBAAIBWmprRHwPu5sHJDEo9yTZkeCqMgygAAL_D2sb42hZU43CtGmANo8xAQADAgADeQADPQQ', 'photo', NULL, 0, '2026-07-30 12:46:08', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (8, 22, 'BQACAgQAAxkBAAIBU2prQcRH0Ackw7ecso8uXkPHegUpAAJXHAAC42hZU1z1oRVF_DFJPQQ', 'document', NULL, 0, '2026-07-30 12:46:34', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (9, 22, NULL, 'text', NULL, 0, '2026-07-30 12:47:20', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (10, 22, NULL, 'text', 'اولین ویدیو تقویم میکنم حامیان ویتینگ میشه', 0, '2026-07-30 12:48:36', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (11, 22, NULL, 'text', NULL, 0, '2026-07-30 12:48:57', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (12, 22, 'CgACAgQAAxkBAAIBf2prSFDAid9uFtLwQeW-jyrzfqHJAALkEAACuU8RUZ4NZwjo2TgOPQQ', 'document', NULL, 0, '2026-07-30 12:49:20', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (13, 22, 'CgACAgQAAxkBAAIBgmprSGrQDrYkts-Nf-wPHwXLPnq6AAIcCgACESEdU_148TradKNOPQQ', 'document', NULL, 0, '2026-07-30 12:49:46', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (14, 22, NULL, 'text', NULL, 0, '2026-07-30 12:50:05', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (15, 22, NULL, 'text', NULL, 0, '2026-07-30 12:50:35', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (16, 22, NULL, 'text', NULL, 0, '2026-07-30 12:51:04', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (17, 22, 'AgACAgQAAxkBAAIBo2prVsYIJopG9BffWWBk_6VBSctcAAIdDWsb42hhU1zXwpKIEQWLAQADAgADeQADPQQ', 'photo', NULL, 0, '2026-07-30 13:51:02', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (18, 26, 'AgACAgQAAxkBAAIBUWprQZeo5Y8vwj8q-e9j2QWG8BarAAL5D2sb42hZUzt1KLOgVYoHAQADAgADeQADPQQ', 'photo', NULL, 0, '2026-07-30 14:19:50', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (19, 29, 'AgACAgQAAxkBAAIBUWprQZeo5Y8vwj8q-e9j2QWG8BarAAL5D2sb42hZUzt1KLOgVYoHAQADAgADeQADPQQ', 'photo', NULL, 0, '2026-07-30 14:41:45', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (20, 33, 'AgACAgQAAxkBAAIBUWprQZeo5Y8vwj8q-e9j2QWG8BarAAL5D2sb42hZUzt1KLOgVYoHAQADAgADeQADPQQ', 'photo', NULL, 0, '2026-07-30 16:23:51', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (21, 29, 'AgACAgQAAxkBAAICnWpr3Xwnf7TqCDQhAAEHLzZvu7JiPAACzw1rG6IUWVNLd0L85-TLgwEAAwIAA3kAAz0E', 'photo', NULL, 0, '2026-07-30 23:25:46', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (22, 12, 'AgACAgQAAxkBAAICw2pr6awLa6MT1ArRpXo-V3C6aQ99AAJUDmsb42hhUx31WeqkL976AQADAgADeAADPQQ', 'photo', NULL, 0, '2026-07-31 00:17:48', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (23, 22, 'CgACAgQAAxkBAAIDMGpslo0nT_0tNgGi2sJWDlSn0LFpAALkEAACuU8RUZ4NZwjo2TgOPQQ', 'document', NULL, 0, '2026-07-31 12:35:24', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (24, 22, NULL, 'text', NULL, 0, '2026-07-31 12:35:27', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (25, 22, NULL, 'text', 'فف', 0, '2026-07-31 12:35:35', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (26, 22, NULL, 'text', '🙏🏻🗿', 0, '2026-07-31 12:35:40', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (27, 22, NULL, 'text', NULL, 0, '2026-07-31 12:36:04', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (28, 22, 'BAACAgQAAxkBAAIDOWpslraxDp2ekkbCTevmYPK866qWAAJnHQAC42hpUxRdFy8oazy9PQQ', 'video', NULL, 0, '2026-07-31 12:36:06', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 22);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (29, 37, 'AgACAgQAAxkBAAIF5mpv1Frex2zm9HC7QjvRuw6eCXu4AAImDWsbwNmAU8ThkeTdDsWAAQADAgADeQADPQQ', 'photo', NULL, 0, '2026-08-02 23:35:50', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 34);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (30, 38, 'AgACAgQAAxkBAAIF62pv1IB5D_yqKugYkhXDSAPL4bsjAAInDWsbwNmAU389r8_hsi5BAQADAgADeQADPQQ', 'photo', NULL, 0, '2026-08-02 23:36:28', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 34);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (31, 45, 'AgACAgQAAxkBAAIHbmpwBbgRShgW-Z4xTwpIdU-msjXpAAJKDWsbwNmAU4tePeK2oOIxAQADAgADeQADPQQ', 'photo', NULL, 0, '2026-08-03 03:06:28', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 45);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (32, 34, 'AgACAgQAAxkBAAIH3GpwCk7kNcPWeEp8luEoj3PKsA-lAAJNDWsbwNmAU4bF8G50no4wAQADAgADeAADPQQ', 'photo', NULL, 0, '2026-08-03 03:26:02', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (33, 47, NULL, 'text', NULL, 0, '2026-08-03 03:39:46', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (34, 52, NULL, 'text', NULL, 0, '2026-08-03 13:29:46', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (35, 66, NULL, 'text', '21.1', 0, '2026-08-06 00:50:57', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (36, 76, NULL, 'text', 'ببیی', 0, '2026-08-06 02:28:28', NULL, NULL, 'public', 0, 1, '2026-08-06T02:29:46.560Z', '6747478812.0', NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (37, 80, NULL, 'text', 'ساتینسکی', 0, '2026-08-06 02:35:43', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (38, 96, NULL, 'text', 'بالایی بولونی لوح', 0, '2026-08-06 05:25:15', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (39, 96, NULL, 'text', NULL, 0, '2026-08-06 05:25:18', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (40, 96, NULL, 'text', NULL, 0, '2026-08-06 05:25:32', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (41, 96, 'AgACAgQAAxkBAAILxmp0GtqoNul8FZxB565KKtnveGDmAAL9DWsbK3WhU5e5B2Fopun2AQADAgADeQADPQQ', 'photo', NULL, 0, '2026-08-06 05:25:45', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (42, 97, NULL, 'text', 'رعععاا', 0, '2026-08-06 05:27:03', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (43, 98, NULL, 'text', 'زیادی ریز', 0, '2026-08-06 05:27:24', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (44, 94, NULL, 'text', NULL, 0, '2026-08-06 05:53:27', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);
INSERT INTO "files" ("id", "button_id", "file_id", "file_type", "caption", "position", "created_at", "message_id", "chat_id", "access_type", "price", "deleted", "deleted_at", "deleted_by", "updated_by", "updated_at", "deleted_root_id") VALUES (45, 100, 'AgACAgQAAxkBAAIMv2qsBB2n98DJG-rWgv_kzTXtoaT-AAKEDmsbwNJhUdYI09O7fG0_AQADAgADeQADPQQ', 'photo', NULL, 0, '2026-09-17 15:15:45', NULL, NULL, 'public', 0, 0, NULL, NULL, NULL, NULL, 0);

-- quick_answers: empty

-- settings: empty

INSERT INTO "user_phones" ("id", "user_id", "phone", "created_at") VALUES (1, 1, '09123456789', '2026-08-06 18:01:27');
INSERT INTO "user_phones" ("id", "user_id", "phone", "created_at") VALUES (2, 1, '09350000000', '2026-08-06 18:04:14');

INSERT INTO "users" ("id", "telegram_id", "username", "first_name", "phone", "last_name") VALUES (1, '6747478812.0', 'MJR_Soli', 'MOJIR', NULL, NULL);
INSERT INTO "users" ("id", "telegram_id", "username", "first_name", "phone", "last_name") VALUES (5, '8167760603.0', 'Mmemelet1234', 'MBBN', NULL, NULL);
INSERT INTO "users" ("id", "telegram_id", "username", "first_name", "phone", "last_name") VALUES (76, '999999', 'test_user', 'Test', NULL, 'User');
INSERT INTO "users" ("id", "telegram_id", "username", "first_name", "phone", "last_name") VALUES (77, '123456', 'test', 'Ali', NULL, 'Test');
INSERT INTO "users" ("id", "telegram_id", "username", "first_name", "phone", "last_name") VALUES (87, '5277206697.0', NULL, 'Roshandel', NULL, NULL);

